sapujagad/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', index, name='index'),
    path('contact-us/', contactus, name='contactus'),
    path("blog/<str:slug>", blogdetail, name="blog_detail"),
    path('lazy_load_blogs/', lazy_load_blogs, name='lazy_load_blogs'),
]

sapujagad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Sapu Jagad Admin"
admin.site.site_title = "Sapu Jagad Admin Portal"
admin.site.index_title = "Welcome to Sapu Jagad Admin Portal"

urlpatterns = [
    path('backoffice/', admin.site.urls),
    path('', include('sapujagad.frontend.urls', namespace='frontend')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

sapujagad/apps/banner/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Banner(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='banner'))
    big_text = models.CharField(max_length=254, blank=True, null=True)
    small_text = models.CharField(max_length=254, blank=True, null=True)
    url = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    # owner = models.ForeignKey('user.User', on_delete=models.CASCADE)
    # kecamatan = models.ForeignKey(
    #     'kecamatan.Kecamatan', on_delete=models.SET_NULL, blank=True, null=True)
    # kelurahan = models.ForeignKey(
    #     'kelurahan.Kelurahan', on_delete=models.SET_NULL, blank=True, null=True)
    # liked_by = models.ManyToManyField('user.User', blank=True, related_name='likes_by')
    # seen_by = models.ManyToManyField('user.User', blank=True, related_name='seens_by')
    # expired = models.DateField('expired', blank=True, null=True)
    # created = AutoCreatedField()
    # price = models.IntegerField(default=0)
    # wa_number = models.CharField('Wa Number', max_length=30, blank=True, null=True)

    def __str__(self):
        return self.big_text

sapujagad/apps/blog/models.py
from sapujagad.core.utils import FilenameGenerator, custom_slugify
from django.db import models
from django.utils.safestring import mark_safe



class Blog(models.Model):
    img1 =  models.ImageField("img 300px 200px", upload_to=FilenameGenerator(
        prefix='banner'))
    title = models.CharField(max_length=254)
    date = models.DateField(blank=True, null=True)
    short_desc = models.CharField(max_length=254, blank=True, null=True)
    long_desc = models.TextField(blank=True, null=True)
    is_active = models.BooleanField("is published", default=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    
    def __str__(self):
        return self.title

    def preview(self):
        return mark_safe('<a href="/blog/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Blog, self).save()

sapujagad/apps/contactus/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Contactus(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    subject = models.CharField(max_length=25, blank=True, null=True)
    message = models.TextField(max_length=254, blank=True, null=True)

    def __str__(self):
        return self.name

sapujagad/apps/menu/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Menu(models.Model):
    name = models.CharField(max_length=254)
    order = models.IntegerField(default=0)
    one_page_url = models.CharField(max_length=254)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

sapujagad/apps/portfolio/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Portfolio(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='portfolio'))
    img_detail =  models.ImageField(upload_to=FilenameGenerator(
        prefix='portfolio'))
    title = models.CharField(max_length=254, blank=True, null=True)
    sub_title = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

sapujagad/apps/pricing/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models

class Pricing(models.Model):
    name = models.CharField(max_length=254)
    price = models.FloatField()
    desc_list = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

sapujagad/apps/service/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Service(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='service'), blank=True, null=True)
    # fa_icon = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

sapujagad/apps/settings/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Settings(models.Model):
    TYPE = (
        ('about_us_background', 'about_us_background'),
        ('about_us_description', 'about_us_description'),
        ('about_us_img', 'about_us_img'),
        ('about_us_title', 'about_us_title'),

        ('address', 'address'),

        ('blog_desc', 'blog_desc'),
        ('blog_title', 'blog_title'),
        
        ('contact_us_title', 'contact_us_title'),
        ('contact_us_description', 'contact_us_description'),
        ('contact_us_description_2', 'contact_us_description_2'),
        
        ('email', 'email'),
        ('facebook_url', 'facebook_url'),
        ('favicon', 'favicon'),
        ('instagram_url', 'instagram_url'),

        ('latitude', 'latitude'),
        ('longitude', 'longitude'),
        ('logo', 'logo'),

        ('our_portfolio_title', 'our_portfolio_title'),
        ('our_portfolio_description', 'our_portfolio_description'),

        ('our_team_title', 'our_team_title'),
        ('our_team_description', 'our_team_description'),

        ('our_service_title', 'our_service_title'),
        ('our_service_description', 'our_service_description'),
        
        ('testimoni_title', 'testimoni_title'),
        ('testimoni_background', 'testimoni_background'),
        
        ('phone', 'phone'),
        ('price_title', 'price_title'),
        ('price_description', 'price_description'),

        ('seo_description', 'SEO Description'),
        ('seo_title', 'SEO Title'),
        ('seo_keywords', 'SEO Keywords'),
        ('seo_image', 'SEO Image'),
        # ('seo_fb_id', 'SEO FbID'),
        
        ('text_before_service', 'text_before_service'),
        ('twitter_url', 'twitter_url'),
        
        ('domain', 'domain'),
        
        ('youtube_url', 'youtube_url'),
    )
    name = models.CharField(max_length=254, choices=TYPE, unique=True)
    text_value = models.TextField(blank=True, null=True)
    img_value =  models.ImageField(upload_to=FilenameGenerator(
        prefix='settings'), blank=True, null=True)

    def __str__(self):
        return self.name

sapujagad/apps/team/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Team(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='team'))
    name = models.CharField(max_length=254, blank=True, null=True)
    position = models.CharField(max_length=254, blank=True, null=True)
    motto = models.CharField(max_length=254, blank=True, null=True)
    fb_link = models.CharField(max_length=254, blank=True, null=True)
    twitter = models.CharField(max_length=254, blank=True, null=True)
    linkedin = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

sapujagad/apps/testimoni/models.py
from sapujagad.core.utils import FilenameGenerator
from django.db import models


class Testimoni(models.Model):
    testimony = models.TextField()
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.testimony

sapujagad/frontend/forms.py
from sapujagad.apps.contactus.models import Contactus
from django import forms


class ContactusForm(forms.ModelForm):
    class Meta:
        model = Contactus
        fields = '__all__'

sapujagad/apps/banner/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/blog/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/contactus/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/menu/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/portfolio/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/pricing/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/service/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/apps/team/views.py
from django.shortcuts import render

# Create your views here.

sapujagad/templates/frontend/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="Imam Asari">
  <title>{{settings.seo_title.text_value}}</title>
  {% include "./meta.html" %}
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/animate.min.css' %}" rel="stylesheet"> 
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link id="css-preset" href="{% static 'css/presets/preset1.css' %}" rel="stylesheet">
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="{{settings.favicon.img_value}}">
  <script type="text/javascript">
    window.CSRF_TOKEN = "{{ csrf_token }}";
  </script>
  {% block extra_header %} {% endblock %}
</head>
<body>
  <div class="preloader"> <i class="fa fa-circle-o-notch fa-spin"></i></div>
  <header id="home">
    <div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
      <div class="carousel-inner">
        {% for banner in banners %}
          <div class="item {% if forloop.counter == 1 %} active {% endif %}" style="background-image: url('{{ banner.img.url }}')">
            <div class="caption">
              <h1 class="animated fadeInLeftBig">{{ banner.big_text|safe }}</h1>
              <p class="animated fadeInRightBig">{{ banner.small_text|safe }} </p>
              <!-- <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Start now</a> -->
            </div>
          </div>
        {% endfor %}
      </div>
      <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
      <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>
      <a id="tohash" href="#services"><i class="fa fa-angle-down"></i></a>
    </div>

    <div class="main-nav">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">
            <h1><img class="img-responsive logo-header" src="{{ settings.logo.img_value }}" alt="logo"></h1>
          </a>                    
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">   
            {% for menu in menus %}
              {% if menu.name == 'home' and homepage %}
                <li class="scroll"><a href="#home">{{menu.name}}</a></li>
              {% else %}
                <li class="scroll"><a href="{{menu.one_page_url}}">{{menu.name}}</a></li>
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
    </div><!--/#main-nav-->
  </header><!--/#home-->

  {% block content %} {% endblock %}

  <footer id="footer">
    <div class="footer-top wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
      <div class="container text-center">
        <div class="footer-logo">
          <a href="index.html"><img class="img-responsive footer-img" src="{{settings.logo.img_value}}" alt=""></a>
        </div>
        <div class="social-icons">
          <ul>
            <li><a class="twitter" href="{{settings.twitter_url.text_value}}" target="_blank"><i class="fa fa-twitter"></i></a></li> 
            <li><a class="facebook" href="{{settings.facebook_url.text_value}}" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a class="instagram" href="{{settings.instagram_url.text_value}}" target="_blank"><i class="fa fa-instagram"></i></a></li>
            <li><a class="youtube" href="{{settings.youtube_url.text_value}}" target="_blank"><i class="fa fa-youtube"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <p>&copy; 2020 Sapujagad</p>
          </div>
          <div class="col-sm-6">
            {% comment %} <p class="pull-right">Crafted by <a href="http://designscrazed.org/">Allie</a></p> {% endcomment %}
          </div>
        </div>
      </div>
    </div>
  </footer>
  
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true&key=AIzaSyCoVB52bTd3g_s0RGR7PZSqfStKxX6eYUI"></script>
  <script type="text/javascript" src="{% static 'js/jquery.inview.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mousescroll.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/smoothscroll.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/lightbox.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/loadmore.js' %}"></script>
  {% block extra_js %} {% endblock %}
</body>
</html>

sapujagad/templates/frontend/blog-detail.html
{% extends 'frontend/base.html' %}
{% block content %}
  <section id="blog" style="padding: 30px 0; ">
    <div class="container">
      <div class="row blog-posts" style="display: flex; justify-content: center;">
        <div class="col-sm-9 wow fadeInUp" data-wow-duration="1000ms" 
            data-wow-delay="400ms" >
          <div class="entry-header" >
              <h1><a href="#">{{blog.title}}</a></h1>
              <span class="date">{{blog.date}}</span>
          </div>
          <div class="post-thumb" style="text-align: center;">
            <img class="img-responsive" src="{{blog.img1.url}}" alt="" style="display: initial;">
          </div>
          <div class="entry-content" style="margin-top: 30px; margin-top: 30px;
              font-size: 1.1em;
              letter-spacing: 0.5px;
              color: black;
              line-height: 1.7em;">
            {{blog.long_desc|safe}}
          </div>
        </div>                          
      </div>
    </div>
  </section><!--/#blog-->

  <section id="blog">
    <div class="container">
      <div class="row">
        <div class="heading text-center col-sm-8 col-sm-offset-2 wow fadeInUp" data-wow-duration="1200ms" data-wow-delay="300ms">
          <h2>{{settings.blog_title.text_value}}</h2>
          <p>{{settings.blog_desc.text_value}}</p>
        </div>
      </div>
      <div class="blog-posts">
        <div class="row" id="posts">
          {% include 'frontend/blogs.html' %}
        </div>
        <div class="load-more wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
          <a id="lazyLoadLink" 
            href="javascript:void(0);" 
            data-page="2" data-link="{% url 'frontend:lazy_load_blogs' %}" 
            class="btn-loadmore"><i class="fa fa-repeat"></i>Artikel lainnya</a>
        </div>                
      </div>
    </div>
  </section>

  {% endblock %}

sapujagad/templates/frontend/blogs.html
{% for blog in blogs %}
<div class="col-sm-4 wow fadeInUp" 
  data-wow-duration="1000ms" data-wow-delay="400ms" style="margin-bottom: 50px">
  <div class="post-thumb">
    <a href="{% url 'frontend:blog_detail' blog.slug %}"><img class="img-responsive" src="{{blog.img1.url}}" alt=""></a> 
  </div>
  <div class="entry-header">
    <h3><a href="{% url 'frontend:blog_detail' blog.slug %}">{{blog.title}}</a></h3>
    <span class="date">{{blog.date}}</span>
    {% comment %} <span class="cetagory">in <strong>Photography</strong></span> {% endcomment %}
  </div>
  <div class="entry-content">
    <p>{{blog.short_desc}}</p>
  </div>
</div>
{% endfor %} 

sapujagad/templates/frontend/meta.html
<meta name="description" content="{{settings.seo_description.text_value}}" />
<meta name="keywords" content="{{settings.seo_keywords.text_value}}" />
<meta name="application-name" content="Web" />

<meta property="fb:app_id" content="{{settings.seo_fb_id.text_value}}" />
<meta property="og:title" content="{{settings.seo_title.text_value}}" />
<meta property="og:type" content="web" />
<meta property="og:image" content="{{settings.website.text_value}}{{settings.seo_image.img_value}}" />
<meta property="og:url" content="{{settings.website.text_value}}" />
<meta property="og:description" content="{{settings.seo_description.text_value}}" />

<meta name="twitter:title" content="{{settings.seo_title.text_value}}" />
<meta name="twitter:description" content="{{settings.seo_description.text_value}}" />
<meta name="twitter:image" content="{{settings.website.text_value}}{{settings.seo_image.img_value}}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:image:width" content="1200" />
<meta name="twitter:image:height" content="630" />